apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-selenium
spec:
  params:
    - name: git_token
      description: the Git Token
    - name: apikey
      description: apikey
    - name: repository
      description: name of the repo
    - name: organisation
      description: name of the org
    - name: branch
      description: name of the branch
    - name: users
      description: Users to be notified
    - name: slack_webhook_url
      description: webhook url
    - name: file
      description: name of the file
  resourcetemplates:
    # CD secret to provide API_KEY to access toolchain information
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        git_token: $(params.git_token)
        slack_webhook_url: $(params.slack_webhook_url)
        apikey: $(params.apikey)
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-selenium
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: organisation
            value: $(params.organisation)
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: users
            value: $(params.users)
          - name: file
            value: $(params.file)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-selenium
spec:
  triggers:
    - binding:
        name: trigger-binding
      template:
        name: trigger-template-selenium
